bot:
  start_time: "09:00"
  end_time: "15:30"
  capital: 1000000
  strategy: "supertrend_adx"
  environment: "live"
risk:
  max_drawdown: 0.2
  position_limit: 10
  stop_loss_type: "trailing"
broker:
  type: "zerodha"
  config: "zerodha.yaml"
ui:
  enabled: true
  port: 8000
alerting:
  email: true
  sms: false
  push: true
logging:
  level: "INFO"
backtesting:
  enabled: false
  config: "backtest.yaml"
