strategies:
  - name: "SupertrendADX"
    params:
      underlying_symbol: "NSE:NIFTY 50"
      adx_threshold: 25
      lot_size: 50
  - name: "MomentumBreakout"
    params:
      underlying_symbol: "NSE:NIFTY 50"
      short_ma_period: 10
      long_ma_period: 30
      lot_size: 50
  - name: "BollingerReversion"
    params:
      underlying_symbol: "NSE:NIFTY 50"
      window: 20
      num_std: 2
      lot_size: 50
